import React from 'react';
import { TYPES } from './_constants';
import * as Items from './_items';

const Map = {
  [TYPES.PAWN_WHITE_BASE]: props => <Items.IconPawnWhiteBase {...props} />,
  [TYPES.BISHOP_WHITE_BASE]: props => <Items.IconBishopWhiteBase {...props} />,
  [TYPES.ROOK_WHITE_BASE]: props => <Items.IconRookWhiteBase {...props} />,
  [TYPES.HORSE_WHITE_BASE]: props => <Items.IconHorseWhiteBase {...props} />,
  [TYPES.QEEN_WHITE_BASE]: props => <Items.IconQeenWhiteBase {...props} />,
  [TYPES.KING_WHITE_BASE]: props => <Items.IconKingWhiteBase {...props} />,
  [TYPES.PAWN_BLACK_BASE]: props => <Items.IconPawnBlackBase {...props} />,
  [TYPES.BISHOP_BLACK_BASE]: props => <Items.IconBishopBlackBase {...props} />,
  [TYPES.ROOK_BLACK_BASE]: props => <Items.IconRookBlackBase {...props} />,
  [TYPES.HORSE_BLACK_BASE]: props => <Items.IconHorseBlackBase {...props} />,
  [TYPES.QEEN_BLACK_BASE]: props => <Items.IconQeenBlackBase {...props} />,
  [TYPES.KING_BLACK_BASE]: props => <Items.IconKingBlackBase {...props} />,

  [TYPES.PAWN_WHITE_SET_1]: props => <Items.IconPawnWhiteSet1 {...props} />,
  [TYPES.BISHOP_WHITE_SET_1]: props => <Items.IconBishopWhiteSet1 {...props} />,
  [TYPES.ROOK_WHITE_SET_1]: props => <Items.IconRookWhiteSet1 {...props} />,
  [TYPES.HORSE_WHITE_SET_1]: props => <Items.IconHorseWhiteSet1 {...props} />,
  [TYPES.QEEN_WHITE_SET_1]: props => <Items.IconQeenWhiteSet1 {...props} />,
  [TYPES.KING_WHITE_SET_1]: props => <Items.IconKingWhiteSet1 {...props} />,
  [TYPES.PAWN_BLACK_SET_1]: props => <Items.IconPawnBlackSet1 {...props} />,
  [TYPES.BISHOP_BLACK_SET_1]: props => <Items.IconBishopBlackSet1 {...props} />,
  [TYPES.ROOK_BLACK_SET_1]: props => <Items.IconRookBlackSet1 {...props} />,
  [TYPES.HORSE_BLACK_SET_1]: props => <Items.IconHorseBlackSet1 {...props} />,
  [TYPES.QEEN_BLACK_SET_1]: props => <Items.IconQeenBlackSet1 {...props} />,
  [TYPES.KING_BLACK_SET_1]: props => <Items.IconKingBlackSet1 {...props} />,

  [TYPES.PAWN_WHITE_SET_2]: props => <Items.IconPawnWhiteSet2 {...props} />,
  [TYPES.BISHOP_WHITE_SET_2]: props => <Items.IconBishopWhiteSet2 {...props} />,
  [TYPES.ROOK_WHITE_SET_2]: props => <Items.IconRookWhiteSet2 {...props} />,
  [TYPES.HORSE_WHITE_SET_2]: props => <Items.IconHorseWhiteSet2 {...props} />,
  [TYPES.QEEN_WHITE_SET_2]: props => <Items.IconQeenWhiteSet2 {...props} />,
  [TYPES.KING_WHITE_SET_2]: props => <Items.IconKingWhiteSet2 {...props} />,
  [TYPES.PAWN_BLACK_SET_2]: props => <Items.IconPawnBlackSet2 {...props} />,
  [TYPES.BISHOP_BLACK_SET_2]: props => <Items.IconBishopBlackSet2 {...props} />,
  [TYPES.ROOK_BLACK_SET_2]: props => <Items.IconRookBlackSet2 {...props} />,
  [TYPES.HORSE_BLACK_SET_2]: props => <Items.IconHorseBlackSet2 {...props} />,
  [TYPES.QEEN_BLACK_SET_2]: props => <Items.IconQeenBlackSet2 {...props} />,
  [TYPES.KING_BLACK_SET_2]: props => <Items.IconKingBlackSet2 {...props} />,

  [TYPES.PAWN_WHITE_SET_3]: props => <Items.IconPawnWhiteSet3 {...props} />,
  [TYPES.BISHOP_WHITE_SET_3]: props => <Items.IconBishopWhiteSet3 {...props} />,
  [TYPES.ROOK_WHITE_SET_3]: props => <Items.IconRookWhiteSet3 {...props} />,
  [TYPES.HORSE_WHITE_SET_3]: props => <Items.IconHorseWhiteSet3 {...props} />,
  [TYPES.QEEN_WHITE_SET_3]: props => <Items.IconQeenWhiteSet3 {...props} />,
  [TYPES.KING_WHITE_SET_3]: props => <Items.IconKingWhiteSet3 {...props} />,
  [TYPES.PAWN_BLACK_SET_3]: props => <Items.IconPawnBlackSet3 {...props} />,
  [TYPES.BISHOP_BLACK_SET_3]: props => <Items.IconBishopBlackSet3 {...props} />,
  [TYPES.ROOK_BLACK_SET_3]: props => <Items.IconRookBlackSet3 {...props} />,
  [TYPES.HORSE_BLACK_SET_3]: props => <Items.IconHorseBlackSet3 {...props} />,
  [TYPES.QEEN_BLACK_SET_3]: props => <Items.IconQeenBlackSet3 {...props} />,
  [TYPES.KING_BLACK_SET_3]: props => <Items.IconKingBlackSet3 {...props} />,

  [TYPES.PAWN_WHITE_SET_4]: props => <Items.IconPawnWhiteSet4 {...props} />,
  [TYPES.BISHOP_WHITE_SET_4]: props => <Items.IconBishopWhiteSet4 {...props} />,
  [TYPES.ROOK_WHITE_SET_4]: props => <Items.IconRookWhiteSet4 {...props} />,
  [TYPES.HORSE_WHITE_SET_4]: props => <Items.IconHorseWhiteSet4 {...props} />,
  [TYPES.QEEN_WHITE_SET_4]: props => <Items.IconQeenWhiteSet4 {...props} />,
  [TYPES.KING_WHITE_SET_4]: props => <Items.IconKingWhiteSet4 {...props} />,
  [TYPES.PAWN_BLACK_SET_4]: props => <Items.IconPawnBlackSet4 {...props} />,
  [TYPES.BISHOP_BLACK_SET_4]: props => <Items.IconBishopBlackSet4 {...props} />,
  [TYPES.ROOK_BLACK_SET_4]: props => <Items.IconRookBlackSet4 {...props} />,
  [TYPES.HORSE_BLACK_SET_4]: props => <Items.IconHorseBlackSet4 {...props} />,
  [TYPES.QEEN_BLACK_SET_4]: props => <Items.IconQeenBlackSet4 {...props} />,
  [TYPES.KING_BLACK_SET_4]: props => <Items.IconKingBlackSet4 {...props} />,

  [TYPES.PAWN_WHITE_SET_5]: props => <Items.IconPawnWhiteSet5 {...props} />,
  [TYPES.BISHOP_WHITE_SET_5]: props => <Items.IconBishopWhiteSet5 {...props} />,
  [TYPES.ROOK_WHITE_SET_5]: props => <Items.IconRookWhiteSet5 {...props} />,
  [TYPES.HORSE_WHITE_SET_5]: props => <Items.IconHorseWhiteSet5 {...props} />,
  [TYPES.QEEN_WHITE_SET_5]: props => <Items.IconQeenWhiteSet5 {...props} />,
  [TYPES.KING_WHITE_SET_5]: props => <Items.IconKingWhiteSet5 {...props} />,
  [TYPES.PAWN_BLACK_SET_5]: props => <Items.IconPawnBlackSet5 {...props} />,
  [TYPES.BISHOP_BLACK_SET_5]: props => <Items.IconBishopBlackSet5 {...props} />,
  [TYPES.ROOK_BLACK_SET_5]: props => <Items.IconRookBlackSet5 {...props} />,
  [TYPES.HORSE_BLACK_SET_5]: props => <Items.IconHorseBlackSet5 {...props} />,
  [TYPES.QEEN_BLACK_SET_5]: props => <Items.IconQeenBlackSet5 {...props} />,
  [TYPES.KING_BLACK_SET_5]: props => <Items.IconKingBlackSet5 {...props} />,
};

export default Map;
