import { COLORS } from '../../_constants';

import { REFS as TYPOGRAPHY_REFS, STYLES as TYPOGRAPHY_STYLES } from '../_constants';

export const COMPONENTS = {
  GENERAL: 'Table',
  ROW: 'TableRow',
  CELL: 'TableCell',
};

export const REFS = {
  SIZES: TYPOGRAPHY_REFS.SIZES,
  SPACING: TYPOGRAPHY_REFS.SIZES,
  TEXT_ALIGN: TYPOGRAPHY_REFS.TEXT_ALIGN,
  COLORS: TYPOGRAPHY_REFS.COLORS,
  BORDER: {
    HORIZONTAL: 'horizontal',
    VERTICAL: 'vertical',
    EVERYWHERE: 'everywhere',
  },
};

export const ROW_REFS = {
  VERTICAL_ALIGN: TYPOGRAPHY_REFS.VERTICAL_ALIGN,
};

export const CELL_REFS = {
  TEXT_ALIGN: TYPOGRAPHY_REFS.TEXT_ALIGN,
};

export const STYLES = {
  FONT_FAMILY: TYPOGRAPHY_STYLES.PARAGRAPH_FONT_FAMILY,
  FONT_WEIGHT: TYPOGRAPHY_STYLES.PARAGRAPH_FONT_WEIGHT,
  LINE_HEIGHT: TYPOGRAPHY_STYLES.PARAGRAPH_LINE_HEIGHT,
  SIZES: TYPOGRAPHY_STYLES.SIZES,
  COLORS: TYPOGRAPHY_STYLES.COLORS,

  TABLE_CELL_BORDER_HORIZONTAL: {
    [REFS.BORDER.HORIZONTAL]: `1px solid ${COLORS.PALE_BLUE}`,
    [REFS.BORDER.VERTICAL]: 'none',
    [REFS.BORDER.EVERYWHERE]: `1px solid ${COLORS.PALE_BLUE}`,
  },

  TABLE_CELL_BORDER_VERTICAL: {
    [REFS.BORDER.HORIZONTAL]: 'none',
    [REFS.BORDER.VERTICAL]: `1px solid ${COLORS.PALE_BLUE}`,
    [REFS.BORDER.EVERYWHERE]: `1px solid ${COLORS.PALE_BLUE}`,
  },
};
