import React, { PureComponent } from 'react';
import Card from '../Card';
import Layout from '../Layout';
import GameNotation from '../GameNotation';
import getFormattedArray from '../_utils/getFormattedArray';

export const MOVES = [
  {
    id: null,
    color: 'w',
    from: 'f2',
    to: 'f3',
    flags: 'n',
    piece: 'p',
    promotion: null,
    san: 'f3',
    ts: null,
    clk: '00:01:00',
    captured: null,
    isCorrect: null,
    isSuccess: null,
    isError: null,
    isNew: null,
    extra: null,
    items: null,
  },
  {
    id: null,
    color: 'b',
    from: 'e7',
    to: 'e6',
    flags: 'n',
    piece: 'p',
    promotion: null,
    san: 'e6',
    ts: null,
    clk: '00:01:01',
    captured: null,
    isCorrect: null,
    isSuccess: null,
    isError: null,
    isNew: null,
    extra: null,
    items: [
      [
        {
          id: null,
          color: 'b',
          from: 'g7',
          to: 'g6',
          flags: 'n',
          piece: 'p',
          promotion: null,
          san: 'g6',
          ts: null,
          clk: null,
          captured: null,
          isCorrect: null,
          isSuccess: null,
          isError: null,
          isNew: null,
          extra: null,
          items: null,
        },
        {
          id: null,
          color: 'w',
          from: 'f3',
          to: 'f4',
          flags: 'n',
          piece: 'p',
          promotion: null,
          san: 'f4',
          ts: null,
          clk: null,
          captured: null,
          isCorrect: null,
          isSuccess: null,
          isError: null,
          isNew: null,
          extra: null,
          items: null,
        },
        {
          id: null,
          color: 'b',
          from: 'g6',
          to: 'g5',
          flags: 'n',
          piece: 'p',
          promotion: null,
          san: 'g5',
          ts: null,
          clk: null,
          captured: null,
          isCorrect: null,
          isSuccess: null,
          isError: null,
          isNew: null,
          extra: null,
          items: null,
        },
        {
          id: null,
          color: 'w',
          from: 'f4',
          to: 'g5',
          flags: 'c',
          piece: 'p',
          promotion: null,
          san: 'fxg5',
          ts: null,
          clk: null,
          captured: 'p',
          isCorrect: null,
          isSuccess: null,
          isError: null,
          isNew: null,
          extra: null,
          items: null,
        },
      ],
    ],
  },
  {
    id: null,
    color: 'w',
    from: 'h2',
    to: 'h3',
    flags: 'n',
    piece: 'p',
    promotion: null,
    san: 'h3',
    ts: null,
    clk: '00:00:57',
    captured: null,
    isCorrect: null,
    isSuccess: null,
    isError: null,
    isNew: null,
    extra: null,
    items: [
      [
        {
          id: null,
          color: 'w',
          from: 'd2',
          to: 'd3',
          flags: 'n',
          piece: 'p',
          promotion: null,
          san: 'd3',
          ts: null,
          clk: null,
          captured: null,
          isCorrect: null,
          isSuccess: null,
          isError: null,
          isNew: null,
          extra: null,
          items: null,
        },
        {
          id: null,
          color: 'b',
          from: 'c7',
          to: 'c6',
          flags: 'n',
          piece: 'p',
          promotion: null,
          san: 'c6',
          ts: null,
          clk: null,
          captured: null,
          isCorrect: null,
          isSuccess: null,
          isError: null,
          isNew: null,
          extra: null,
          items: [
            [
              {
                id: null,
                color: 'b',
                from: 'g7',
                to: 'g6',
                flags: 'n',
                piece: 'p',
                promotion: null,
                san: 'g6',
                ts: null,
                clk: null,
                captured: null,
                isCorrect: null,
                isSuccess: null,
                isError: null,
                isNew: null,
                extra: null,
                items: null,
              },
              {
                id: null,
                color: 'w',
                from: 'f3',
                to: 'f4',
                flags: 'n',
                piece: 'p',
                promotion: null,
                san: 'f4',
                ts: null,
                clk: null,
                captured: null,
                isCorrect: null,
                isSuccess: null,
                isError: null,
                isNew: null,
                extra: null,
                items: null,
              },
              {
                id: null,
                color: 'b',
                from: 'g6',
                to: 'g5',
                flags: 'n',
                piece: 'p',
                promotion: null,
                san: 'g5',
                ts: null,
                clk: null,
                captured: null,
                isCorrect: null,
                isSuccess: null,
                isError: null,
                isNew: null,
                extra: null,
                items: null,
              },
              {
                id: null,
                color: 'w',
                from: 'f4',
                to: 'g5',
                flags: 'c',
                piece: 'p',
                promotion: null,
                san: 'fxg5',
                ts: null,
                clk: null,
                captured: 'p',
                isCorrect: null,
                isSuccess: null,
                isError: null,
                isNew: null,
                extra: null,
                items: null,
              },
              {
                id: null,
                color: 'b',
                from: 'f7',
                to: 'f6',
                flags: 'n',
                piece: 'p',
                promotion: null,
                san: 'f6',
                ts: null,
                clk: null,
                captured: null,
                isCorrect: null,
                isSuccess: null,
                isError: null,
                isNew: null,
                extra: null,
                items: null,
              },
              {
                id: null,
                color: 'w',
                from: 'g5',
                to: 'f6',
                flags: 'c',
                piece: 'p',
                promotion: null,
                san: 'gxf6',
                ts: null,
                clk: null,
                captured: 'p',
                isCorrect: null,
                isSuccess: null,
                isError: null,
                isNew: null,
                extra: null,
                items: null,
              },
            ],
          ],
        },
        {
          id: null,
          color: 'w',
          from: 'd3',
          to: 'd4',
          flags: 'n',
          piece: 'p',
          promotion: null,
          san: 'd4',
          ts: null,
          clk: null,
          captured: null,
          isCorrect: null,
          isSuccess: null,
          isError: null,
          isNew: null,
          extra: null,
          items: [
            [
              {
                id: null,
                color: 'w',
                from: 'h2',
                to: 'h3',
                flags: 'n',
                piece: 'p',
                promotion: null,
                san: 'h3',
                ts: null,
                clk: null,
                captured: null,
                isCorrect: null,
                isSuccess: null,
                isError: null,
                isNew: null,
                extra: null,
                items: null,
              },
              {
                id: null,
                color: 'b',
                from: 'g7',
                to: 'g6',
                flags: 'n',
                piece: 'p',
                promotion: null,
                san: 'g6',
                ts: null,
                clk: null,
                captured: null,
                isCorrect: null,
                isSuccess: null,
                isError: null,
                isNew: null,
                extra: null,
                items: null,
              },
              {
                id: null,
                color: 'w',
                from: 'h3',
                to: 'h4',
                flags: 'n',
                piece: 'p',
                promotion: null,
                san: 'h4',
                ts: null,
                clk: null,
                captured: null,
                isCorrect: null,
                isSuccess: null,
                isError: null,
                isNew: null,
                extra: null,
                items: null,
              },
              {
                id: null,
                color: 'b',
                from: 'g6',
                to: 'g5',
                flags: 'n',
                piece: 'p',
                promotion: null,
                san: 'g5',
                ts: null,
                clk: null,
                captured: null,
                isCorrect: null,
                isSuccess: null,
                isError: null,
                isNew: null,
                extra: null,
                items: null,
              },
              {
                id: null,
                color: 'w',
                from: 'h4',
                to: 'g5',
                flags: 'c',
                piece: 'p',
                promotion: null,
                san: 'hxg5',
                ts: null,
                clk: null,
                captured: 'p',
                isCorrect: null,
                isSuccess: null,
                isError: null,
                isNew: null,
                extra: null,
                items: null,
              },
              {
                id: null,
                color: 'b',
                from: 'h7',
                to: 'h6',
                flags: 'n',
                piece: 'p',
                promotion: null,
                san: 'h6',
                ts: null,
                clk: null,
                captured: null,
                isCorrect: null,
                isSuccess: null,
                isError: null,
                isNew: null,
                extra: null,
                items: null,
              },
              {
                id: null,
                color: 'w',
                from: 'g5',
                to: 'h6',
                flags: 'c',
                piece: 'p',
                promotion: null,
                san: 'gxh6',
                ts: null,
                clk: null,
                captured: 'p',
                isCorrect: null,
                isSuccess: null,
                isError: null,
                isNew: null,
                extra: null,
                items: null,
              },
            ],
          ],
        },
        {
          id: null,
          color: 'b',
          from: 'c6',
          to: 'c5',
          flags: 'n',
          piece: 'p',
          promotion: null,
          san: 'c5',
          ts: null,
          clk: null,
          captured: null,
          isCorrect: null,
          isSuccess: null,
          isError: null,
          isNew: null,
          extra: null,
          items: null,
        },
        {
          id: null,
          color: 'w',
          from: 'd4',
          to: 'c5',
          flags: 'c',
          piece: 'p',
          promotion: null,
          san: 'dxc5',
          ts: null,
          clk: null,
          captured: 'p',
          isCorrect: null,
          isSuccess: null,
          isError: null,
          isNew: null,
          extra: null,
          items: null,
        },
        {
          id: null,
          color: 'b',
          from: 'd7',
          to: 'd6',
          flags: 'n',
          piece: 'p',
          promotion: null,
          san: 'd6',
          ts: null,
          clk: null,
          captured: null,
          isCorrect: null,
          isSuccess: null,
          isError: null,
          isNew: null,
          extra: null,
          items: null,
        },
        {
          id: null,
          color: 'w',
          from: 'c5',
          to: 'd6',
          flags: 'c',
          piece: 'p',
          promotion: null,
          san: 'cxd6',
          ts: null,
          clk: null,
          captured: 'p',
          isCorrect: null,
          isSuccess: null,
          isError: null,
          isNew: null,
          extra: null,
          items: null,
        },
      ],
    ],
  },
  {
    id: null,
    color: 'b',
    from: 'a7',
    to: 'a6',
    flags: 'n',
    piece: 'p',
    promotion: null,
    san: 'a6',
    ts: null,
    clk: '00:01:01',
    captured: null,
    isCorrect: null,
    isSuccess: null,
    isError: null,
    isNew: null,
    extra: null,
    items: null,
  },
  {
    id: null,
    color: 'w',
    from: 'h3',
    to: 'h4',
    flags: 'n',
    piece: 'p',
    promotion: null,
    san: 'h4',
    ts: null,
    clk: '00:00:57',
    captured: null,
    isCorrect: null,
    isSuccess: null,
    isError: null,
    isNew: null,
    extra: null,
    items: [
      [
        {
          id: null,
          color: 'w',
          from: 'd2',
          to: 'd3',
          flags: 'n',
          piece: 'p',
          promotion: null,
          san: 'd3',
          ts: null,
          clk: null,
          captured: null,
          isCorrect: null,
          isSuccess: null,
          isError: null,
          isNew: null,
          extra: null,
          items: null,
        },
        {
          id: null,
          color: 'b',
          from: 'e6',
          to: 'e5',
          flags: 'n',
          piece: 'p',
          promotion: null,
          san: 'e5',
          ts: null,
          clk: null,
          captured: null,
          isCorrect: null,
          isSuccess: null,
          isError: null,
          isNew: null,
          extra: null,
          items: null,
        },
        {
          id: null,
          color: 'w',
          from: 'd3',
          to: 'd4',
          flags: 'n',
          piece: 'p',
          promotion: null,
          san: 'd4',
          ts: null,
          clk: null,
          captured: null,
          isCorrect: null,
          isSuccess: null,
          isError: null,
          isNew: null,
          extra: null,
          items: [
            [
              {
                id: null,
                color: 'w',
                from: 'f3',
                to: 'f4',
                flags: 'n',
                piece: 'p',
                promotion: null,
                san: 'f4',
                ts: null,
                clk: null,
                captured: null,
                isCorrect: null,
                isSuccess: null,
                isError: null,
                isNew: null,
                extra: null,
                items: null,
              },
              {
                id: null,
                color: 'b',
                from: 'g7',
                to: 'g6',
                flags: 'n',
                piece: 'p',
                promotion: null,
                san: 'g6',
                ts: null,
                clk: null,
                captured: null,
                isCorrect: null,
                isSuccess: null,
                isError: null,
                isNew: null,
                extra: null,
                items: [
                  [
                    {
                      id: null,
                      color: 'b',
                      from: 'd7',
                      to: 'd6',
                      flags: 'n',
                      piece: 'p',
                      promotion: null,
                      san: 'd6',
                      ts: null,
                      clk: null,
                      captured: null,
                      isCorrect: null,
                      isSuccess: null,
                      isError: null,
                      isNew: null,
                      extra: null,
                      items: null,
                    },
                    {
                      id: null,
                      color: 'w',
                      from: 'c2',
                      to: 'c3',
                      flags: 'n',
                      piece: 'p',
                      promotion: null,
                      san: 'c3',
                      ts: null,
                      clk: null,
                      captured: null,
                      isCorrect: null,
                      isSuccess: null,
                      isError: null,
                      isNew: null,
                      extra: null,
                      items: null,
                    },
                    {
                      id: null,
                      color: 'b',
                      from: 'd6',
                      to: 'd5',
                      flags: 'n',
                      piece: 'p',
                      promotion: null,
                      san: 'd5',
                      ts: null,
                      clk: null,
                      captured: null,
                      isCorrect: null,
                      isSuccess: null,
                      isError: null,
                      isNew: null,
                      extra: null,
                      items: null,
                    },
                    {
                      id: null,
                      color: 'w',
                      from: 'c3',
                      to: 'c4',
                      flags: 'n',
                      piece: 'p',
                      promotion: null,
                      san: 'c4',
                      ts: null,
                      clk: null,
                      captured: null,
                      isCorrect: null,
                      isSuccess: null,
                      isError: null,
                      isNew: null,
                      extra: null,
                      items: [
                        [
                          {
                            id: null,
                            color: 'w',
                            from: 'g2',
                            to: 'g3',
                            flags: 'n',
                            piece: 'p',
                            promotion: null,
                            san: 'g3',
                            ts: null,
                            clk: null,
                            captured: null,
                            isCorrect: null,
                            isSuccess: null,
                            isError: null,
                            isNew: null,
                            extra: null,
                            items: null,
                          },
                          {
                            id: null,
                            color: 'b',
                            from: 'h7',
                            to: 'h6',
                            flags: 'n',
                            piece: 'p',
                            promotion: null,
                            san: 'h6',
                            ts: null,
                            clk: null,
                            captured: null,
                            isCorrect: null,
                            isSuccess: null,
                            isError: null,
                            isNew: null,
                            extra: null,
                            items: null,
                          },
                          {
                            id: null,
                            color: 'w',
                            from: 'g3',
                            to: 'g4',
                            flags: 'n',
                            piece: 'p',
                            promotion: null,
                            san: 'g4',
                            ts: null,
                            clk: null,
                            captured: null,
                            isCorrect: null,
                            isSuccess: null,
                            isError: null,
                            isNew: null,
                            extra: null,
                            items: null,
                          },
                          {
                            id: null,
                            color: 'b',
                            from: 'h6',
                            to: 'h5',
                            flags: 'n',
                            piece: 'p',
                            promotion: null,
                            san: 'h5',
                            ts: null,
                            clk: null,
                            captured: null,
                            isCorrect: null,
                            isSuccess: null,
                            isError: null,
                            isNew: null,
                            extra: null,
                            items: null,
                          },
                          {
                            id: null,
                            color: 'w',
                            from: 'g4',
                            to: 'h5',
                            flags: 'c',
                            piece: 'p',
                            promotion: null,
                            san: 'gxh5',
                            ts: null,
                            clk: null,
                            captured: 'p',
                            isCorrect: null,
                            isSuccess: null,
                            isError: null,
                            isNew: null,
                            extra: null,
                            items: null,
                          },
                        ],
                      ],
                    },
                    {
                      id: null,
                      color: 'b',
                      from: 'd5',
                      to: 'c4',
                      flags: 'c',
                      piece: 'p',
                      promotion: null,
                      san: 'dxc4',
                      ts: null,
                      clk: null,
                      captured: 'p',
                      isCorrect: null,
                      isSuccess: null,
                      isError: null,
                      isNew: null,
                      extra: null,
                      items: null,
                    },
                  ],
                ],
              },
              {
                id: null,
                color: 'w',
                from: 'f4',
                to: 'f5',
                flags: 'n',
                piece: 'p',
                promotion: null,
                san: 'f5',
                ts: null,
                clk: null,
                captured: null,
                isCorrect: null,
                isSuccess: null,
                isError: null,
                isNew: null,
                extra: null,
                items: null,
              },
              {
                id: null,
                color: 'b',
                from: 'g6',
                to: 'f5',
                flags: 'c',
                piece: 'p',
                promotion: null,
                san: 'gxf5',
                ts: null,
                clk: null,
                captured: 'p',
                isCorrect: null,
                isSuccess: null,
                isError: null,
                isNew: null,
                extra: null,
                items: null,
              },
              {
                id: null,
                color: 'w',
                from: 'g2',
                to: 'g3',
                flags: 'n',
                piece: 'p',
                promotion: null,
                san: 'g3',
                ts: null,
                clk: null,
                captured: null,
                isCorrect: null,
                isSuccess: null,
                isError: null,
                isNew: null,
                extra: null,
                items: null,
              },
              {
                id: null,
                color: 'b',
                from: 'f5',
                to: 'f4',
                flags: 'n',
                piece: 'p',
                promotion: null,
                san: 'f4',
                ts: null,
                clk: null,
                captured: null,
                isCorrect: null,
                isSuccess: null,
                isError: null,
                isNew: null,
                extra: null,
                items: null,
              },
              {
                id: null,
                color: 'w',
                from: 'g3',
                to: 'f4',
                flags: 'c',
                piece: 'p',
                promotion: null,
                san: 'gxf4',
                ts: null,
                clk: null,
                captured: 'p',
                isCorrect: null,
                isSuccess: null,
                isError: null,
                isNew: null,
                extra: null,
                items: null,
              },
              {
                id: null,
                color: 'b',
                from: 'e5',
                to: 'e4',
                flags: 'n',
                piece: 'p',
                promotion: null,
                san: 'e4',
                ts: null,
                clk: null,
                captured: null,
                isCorrect: null,
                isSuccess: null,
                isError: null,
                isNew: null,
                extra: null,
                items: null,
              },
              {
                id: null,
                color: 'w',
                from: 'd3',
                to: 'e4',
                flags: 'c',
                piece: 'p',
                promotion: null,
                san: 'dxe4',
                ts: null,
                clk: null,
                captured: 'p',
                isCorrect: null,
                isSuccess: null,
                isError: null,
                isNew: null,
                extra: null,
                items: null,
              },
              {
                id: null,
                color: 'b',
                from: 'd7',
                to: 'd5',
                flags: 'b',
                piece: 'p',
                promotion: null,
                san: 'd5',
                ts: null,
                clk: null,
                captured: null,
                isCorrect: null,
                isSuccess: null,
                isError: null,
                isNew: null,
                extra: null,
                items: null,
              },
              {
                id: null,
                color: 'w',
                from: 'e4',
                to: 'e5',
                flags: 'n',
                piece: 'p',
                promotion: null,
                san: 'e5',
                ts: null,
                clk: null,
                captured: null,
                isCorrect: null,
                isSuccess: null,
                isError: null,
                isNew: null,
                extra: null,
                items: null,
              },
              {
                id: null,
                color: 'b',
                from: 'f7',
                to: 'f6',
                flags: 'n',
                piece: 'p',
                promotion: null,
                san: 'f6',
                ts: null,
                clk: null,
                captured: null,
                isCorrect: null,
                isSuccess: null,
                isError: null,
                isNew: null,
                extra: null,
                items: null,
              },
              {
                id: null,
                color: 'w',
                from: 'e5',
                to: 'f6',
                flags: 'c',
                piece: 'p',
                promotion: null,
                san: 'exf6',
                ts: null,
                clk: null,
                captured: 'p',
                isCorrect: null,
                isSuccess: null,
                isError: null,
                isNew: null,
                extra: null,
                items: null,
              },
            ],
          ],
        },
        {
          id: null,
          color: 'b',
          from: 'e5',
          to: 'd4',
          flags: 'c',
          piece: 'p',
          promotion: null,
          san: 'exd4',
          ts: null,
          clk: null,
          captured: 'p',
          isCorrect: null,
          isSuccess: null,
          isError: null,
          isNew: null,
          extra: null,
          items: null,
        },
        {
          id: null,
          color: 'w',
          from: 'c2',
          to: 'c3',
          flags: 'n',
          piece: 'p',
          promotion: null,
          san: 'c3',
          ts: null,
          clk: null,
          captured: null,
          isCorrect: null,
          isSuccess: null,
          isError: null,
          isNew: null,
          extra: null,
          items: null,
        },
        {
          id: null,
          color: 'b',
          from: 'd4',
          to: 'c3',
          flags: 'c',
          piece: 'p',
          promotion: null,
          san: 'dxc3',
          ts: null,
          clk: null,
          captured: 'p',
          isCorrect: null,
          isSuccess: null,
          isError: null,
          isNew: null,
          extra: null,
          items: null,
        },
        {
          id: null,
          color: 'w',
          from: 'b2',
          to: 'c3',
          flags: 'c',
          piece: 'p',
          promotion: null,
          san: 'bxc3',
          ts: null,
          clk: null,
          captured: 'p',
          isCorrect: null,
          isSuccess: null,
          isError: null,
          isNew: null,
          extra: null,
          items: null,
        },
        {
          id: null,
          color: 'b',
          from: 'd7',
          to: 'd6',
          flags: 'n',
          piece: 'p',
          promotion: null,
          san: 'd6',
          ts: null,
          clk: null,
          captured: null,
          isCorrect: null,
          isSuccess: null,
          isError: null,
          isNew: null,
          extra: null,
          items: null,
        },
        {
          id: null,
          color: 'w',
          from: 'c3',
          to: 'c4',
          flags: 'n',
          piece: 'p',
          promotion: null,
          san: 'c4',
          ts: null,
          clk: null,
          captured: null,
          isCorrect: null,
          isSuccess: null,
          isError: null,
          isNew: null,
          extra: null,
          items: null,
        },
        {
          id: null,
          color: 'b',
          from: 'd6',
          to: 'd5',
          flags: 'n',
          piece: 'p',
          promotion: null,
          san: 'd5',
          ts: null,
          clk: null,
          captured: null,
          isCorrect: null,
          isSuccess: null,
          isError: null,
          isNew: null,
          extra: null,
          items: null,
        },
        {
          id: null,
          color: 'w',
          from: 'c4',
          to: 'd5',
          flags: 'c',
          piece: 'p',
          promotion: null,
          san: 'cxd5',
          ts: null,
          clk: null,
          captured: 'p',
          isCorrect: null,
          isSuccess: null,
          isError: null,
          isNew: null,
          extra: null,
          items: null,
        },
      ],
    ],
  },
  {
    id: null,
    color: 'b',
    from: 'a6',
    to: 'a5',
    flags: 'n',
    piece: 'p',
    promotion: null,
    san: 'a5',
    ts: null,
    clk: '00:01:01',
    captured: null,
    isCorrect: null,
    isSuccess: null,
    isError: null,
    isNew: null,
    extra: null,
    items: null,
  },
  {
    id: null,
    color: 'w',
    from: 'h4',
    to: 'h5',
    flags: 'n',
    piece: 'p',
    promotion: null,
    san: 'h5',
    ts: null,
    clk: '00:00:57',
    captured: null,
    isCorrect: null,
    isSuccess: null,
    isError: null,
    isNew: null,
    extra: null,
    items: null,
  },
  {
    id: null,
    color: 'b',
    from: 'a5',
    to: 'a4',
    flags: 'n',
    piece: 'p',
    promotion: null,
    san: 'a4',
    ts: null,
    clk: '00:01:01',
    captured: null,
    isCorrect: null,
    isSuccess: null,
    isError: null,
    isNew: null,
    extra: null,
    items: null,
  },
  {
    id: null,
    color: 'w',
    from: 'h5',
    to: 'h6',
    flags: 'n',
    piece: 'p',
    promotion: null,
    san: 'h6',
    ts: null,
    clk: '00:00:57',
    captured: null,
    isCorrect: null,
    isSuccess: null,
    isError: null,
    isNew: null,
    extra: null,
    items: null,
  },
  {
    id: null,
    color: 'b',
    from: 'a4',
    to: 'a3',
    flags: 'n',
    piece: 'p',
    promotion: null,
    san: 'a3',
    ts: null,
    clk: '00:01:02',
    captured: null,
    isCorrect: null,
    isSuccess: null,
    isError: null,
    isNew: null,
    extra: null,
    items: null,
  },
  {
    id: null,
    color: 'w',
    from: 'h6',
    to: 'g7',
    flags: 'c',
    piece: 'p',
    promotion: null,
    san: 'hxg7',
    ts: null,
    clk: '00:00:57',
    captured: 'p',
    isCorrect: null,
    isSuccess: null,
    isError: null,
    isNew: null,
    extra: null,
    items: null,
  },
  {
    id: null,
    color: 'b',
    from: 'a3',
    to: 'b2',
    flags: 'c',
    piece: 'p',
    promotion: null,
    san: 'axb2',
    ts: null,
    clk: '00:01:01',
    captured: 'p',
    isCorrect: null,
    isSuccess: null,
    isError: null,
    isNew: null,
    extra: null,
    items: null,
  },
  {
    id: null,
    color: 'w',
    from: 'g7',
    to: 'h8',
    flags: 'cp',
    piece: 'p',
    promotion: 'q',
    san: 'gxh8=Q',
    ts: null,
    clk: '00:00:56',
    captured: 'r',
    isCorrect: null,
    isSuccess: null,
    isError: null,
    isNew: true,
    extra: null,
    items: null,
  },
  {
    id: null,
    color: 'b',
    from: 'b2',
    to: 'a1',
    flags: 'cp',
    piece: 'p',
    promotion: 'r',
    san: 'bxa1=R',
    ts: null,
    clk: '00:00:57',
    captured: 'r',
    isCorrect: null,
    isSuccess: null,
    isError: null,
    isNew: true,
    extra: null,
    items: null,
  },
  {
    color: 'b',
    from: 'g8',
    to: 'h6',
    flags: 'c',
    piece: 'n',
    captured: 'b',
    san: 'Nxh6',
    passedTime: '2:34',
    extra: {
      drawRequest: '2020-03-31T16:31:48.000Z',
      drawDeny: '2020-03-31T16:31:55.000Z',
    },
  },
  {
    showCountdown: true,
    ts: 10000,
  },
];

export default class GameNotationExample extends PureComponent {
  constructor(props) {
    super(props);
    this.state = {
      moveId: [0],
      moves: MOVES,
    };
  }

  onChangeMove = move => {
    this.setState({ moveId: move.moveId });
  };

  onRemoveLine = ({ line }) => {
    const moveId = !!line?.length && line[0] && line[0].length && line[0][0] && line[0][0].moveId;
    const removeLine = moveId.length && moveId.slice(0, -1);
    console.log(removeLine) // eslint-disable-line
  };

  render() {
    const { moveId, moves } = this.state;
    const columnLabels = { whiteMove: 'Ход белых', blackMove: 'Ход черных' };
    return (
      <Layout>
        <Layout.Section type="normal">
          <Card style={{ width: '600px', height: '900px' }} background="white">
            <GameNotation
              active={moveId.join('-')}
              notation={getFormattedArray(moves)}
              columnLabels={columnLabels}
              onChangeMove={this.onChangeMove}
              onRemoveLine={this.onRemoveLine}
              settings={{ notationIcon: true, notationFull: false, isBlocked: false }}
            />
          </Card>
        </Layout.Section>
      </Layout>
    );
  }
}
