import { REFS as TYPOGRAPHY_REFS, STYLES as TYPOGRAPHY_STYLES, HEADING_SIZES } from '../_constants';

export const COMPONENTS = {
  GENERAL: 'Heading',
};

export const REFS = {
  SIZES: HEADING_SIZES,
  TEXT_ALIGN: TYPOGRAPHY_REFS.TEXT_ALIGN,
  COLORS: TYPOGRAPHY_REFS.COLORS,
};

export const STYLES = {
  FONT_FAMILY: TYPOGRAPHY_STYLES.HEADING_FONT_FAMILY,
  FONT_WEIGHT: TYPOGRAPHY_STYLES.HEADING_FONT_WEIGHT,
  LINE_HEIGHT: TYPOGRAPHY_STYLES.HEADING_LINE_HEIGHT,
  MARGIN: TYPOGRAPHY_STYLES.HEADING_MARGIN,
  SIZES: TYPOGRAPHY_STYLES.HEADING_SIZES,
  COLORS: TYPOGRAPHY_STYLES.COLORS,
};
