import { REFS as TYPOGRAPHY_REFS, STYLES as TYPOGRAPHY_STYLES } from '../_constants';

export const COMPONENTS = {
  GENERAL: 'Span',
};

export const REFS = {
  SIZES: TYPOGRAPHY_REFS.SIZES,
  COLORS: TYPOGRAPHY_REFS.COLORS,
  WEIGHTS: TYPOGRAPHY_REFS.WEIGHTS,
};

export const STYLES = {
  SIZES: TYPOGRAPHY_STYLES.SIZES,
  WEIGHTS: TYPOGRAPHY_STYLES.WEIGHTS,
  COLORS: TYPOGRAPHY_STYLES.COLORS,
};
