import { REFS as TYPOGRAPHY_REFS, STYLES as TYPOGRAPHY_STYLES } from '../_constants';

export const COMPONENTS = {
  GENERAL: 'List',
  ITEM: 'Item',
};

export const REFS = {
  TYPES: {
    UL: 'ul',
    OL: 'ol',
  },
  SIZES: TYPOGRAPHY_REFS.SIZES,
  COLORS: TYPOGRAPHY_REFS.COLORS,
};

export const STYLES = {
  FONT_FAMILY: TYPOGRAPHY_STYLES.PARAGRAPH_FONT_FAMILY,
  FONT_WEIGHT: TYPOGRAPHY_STYLES.PARAGRAPH_FONT_WEIGHT,
  LINE_HEIGHT: TYPOGRAPHY_STYLES.PARAGRAPH_LINE_HEIGHT,
  MARGIN: TYPOGRAPHY_STYLES.PARAGRAPH_MARGIN,
  ITEM_MARGIN: TYPOGRAPHY_STYLES.PARAGRAPH_MARGIN,
  SIZES: TYPOGRAPHY_STYLES.SIZES,
  COLORS: TYPOGRAPHY_STYLES.COLORS,
};
