import { REFS as TYPOGRAPHY_REFS, STYLES as TYPOGRAPHY_STYLES } from '../_constants';

export const COMPONENTS = {
  GENERAL: 'Block',
};

export const REFS = {
  SIZES: TYPOGRAPHY_REFS.SIZES,
  MARGIN: TYPOGRAPHY_REFS.SIZES,
  PADDING: TYPOGRAPHY_REFS.SIZES,
  TEXT_ALIGN: TYPOGRAPHY_REFS.TEXT_ALIGN,
  COLORS: TYPOGRAPHY_REFS.COLORS,
};

export const STYLES = {
  FONT_FAMILY: TYPOGRAPHY_STYLES.PARAGRAPH_FONT_FAMILY,
  FONT_WEIGHT: TYPOGRAPHY_STYLES.PARAGRAPH_FONT_WEIGHT,
  LINE_HEIGHT: TYPOGRAPHY_STYLES.PARAGRAPH_LINE_HEIGHT,
  SIZES: TYPOGRAPHY_STYLES.SIZES,
  COLORS: TYPOGRAPHY_STYLES.COLORS,
};
