import colors from '../colors';

export default {
  normal: {
    overlayBackgroundColors: {
      normal: 'linear-gradient(0deg, rgba(0, 0, 0, 0), rgba(0, 0, 0, 0))',
      hovered: 'linear-gradient(0deg, rgba(0, 0, 0, 0.1), rgba(0, 0, 0, 0.1))',
      pressed: 'linear-gradient(0deg, rgba(0, 0, 0, 0.15), rgba(0, 0, 0, 0.15))',
      disabled: 'linear-gradient(0deg, rgba(0, 0, 0, 0), rgba(0, 0, 0, 0))',
    },
    backgroundColors: {
      brand: {
        normal: colors.brand.primary.medium,
        hovered: colors.brand.primary.medium,
        pressed: colors.brand.primary.medium,
        disabled: colors.base.onBase.high,
      },
      outline: {
        normal: colors.transparent,
        hovered: colors.brand.primary.medium,
        pressed: colors.brand.primary.medium,
        disabled: colors.base.onBase.high,
        active: colors.brand.primary.medium,
      },
      primary: {
        normal: colors.transparent,
        hovered: colors.brand.primary.pale,
        pressed: colors.brand.primary.pale,
        disabled: colors.base.onBase.high,
        active: colors.brand.primary.medium,
      },
      secondary: {
        normal: colors.base.background.main,
        hovered: colors.brand.primary.medium,
        pressed: colors.brand.primary.medium,
        disabled: colors.base.onBase.high,
      },
      muted: {
        normal: colors.brand.primary.pale,
        hovered: colors.brand.primary.medium,
        pressed: colors.brand.primary.medium,
        disabled: colors.base.onBase.high,
      },
      negative: {
        normal: colors.accents.error.medium,
        hovered: colors.accents.error.medium,
        pressed: colors.accents.error.medium,
        disabled: colors.base.onBase.high,
      },
      negativePrimary: {
        normal: colors.transparent,
        hovered: colors.transparent,
        pressed: colors.transparent,
        disabled: colors.transparent,
      },
      positive: {
        normal: colors.accents.success.main,
        hovered: colors.accents.success.main,
        pressed: colors.accents.success.main,
        disabled: colors.base.onBase.high,
      },
      premium: {
        normal: colors.premium.background.normal,
        hovered: colors.premium.background.normal,
        pressed: colors.premium.background.normal,
        disabled: colors.base.onBase.high,
      },
    },
    borderColors: {
      brand: {
        normal: colors.brand.primary.medium,
        hovered: colors.transparent,
        pressed: colors.transparent,
        disabled: colors.base.onBase.high,
      },
      outline: {
        normal: colors.base.onContrast.medium,
        hovered: colors.transparent,
        pressed: colors.transparent,
        disabled: colors.base.onBase.high,
      },
      primary: {
        normal: colors.transparent,
        hovered: colors.transparent,
        pressed: colors.transparent,
        disabled: colors.base.onBase.high,
      },
      secondary: {
        normal: colors.base.background.main,
        hovered: colors.transparent,
        pressed: colors.transparent,
        disabled: colors.base.onBase.high,
      },
      muted: {
        normal: colors.brand.primary.pale,
        hovered: colors.transparent,
        pressed: colors.transparent,
        disabled: colors.base.onBase.high,
      },
      negative: {
        normal: colors.accents.error.medium,
        hovered: colors.transparent,
        pressed: colors.transparent,
        disabled: colors.transparent,
      },
      negativePrimary: {
        normal: colors.transparent,
        hovered: colors.transparent,
        pressed: colors.transparent,
        disabled: colors.base.onBase.high,
      },
      positive: {
        normal: colors.accents.success.main,
        hovered: colors.transparent,
        pressed: colors.transparent,
        disabled: colors.base.onBase.high,
      },
      premium: {
        normal: colors.none,
        hovered: colors.none,
        pressed: colors.none,
        disabled: colors.base.onBase.high,
      },
    },
    colors: {
      brand: {
        normal: colors.white,
        hovered: colors.white,
        pressed: colors.white,
        disabled: colors.base.onBase.low,
      },
      outline: {
        normal: colors.base.background.main,
        hovered: colors.white,
        pressed: colors.white,
        disabled: colors.base.onBase.low,
        active: colors.white,
      },
      primary: {
        normal: colors.base.background.main,
        hovered: colors.base.background.main,
        pressed: colors.base.background.main,
        disabled: colors.base.onBase.low,
      },
      secondary: {
        normal: colors.base.onBase.high,
        hovered: colors.white,
        pressed: colors.white,
        disabled: colors.base.onBase.low,
      },
      muted: {
        normal: colors.base.onContrast.main,
        hovered: colors.white,
        pressed: colors.white,
        disabled: colors.base.onBase.low,
      },
      negative: {
        normal: colors.white,
        hovered: colors.white,
        pressed: colors.white,
        disabled: colors.base.onBase.low,
      },
      negativePrimary: {
        normal: colors.accents.error.main,
        hovered: colors.accents.error.medium,
        pressed: colors.accents.error.deep,
        disabled: colors.base.onBase.disabled,
      },
      positive: {
        normal: colors.white,
        hovered: colors.white,
        pressed: colors.white,
        disabled: colors.base.onBase.low,
      },
      premium: {
        normal: colors.white,
        hovered: colors.white,
        pressed: colors.white,
        disabled: colors.base.onBase.low,
      },
    },
  },
  inverse: {
    overlayBackgroundColors: {
      normal: 'linear-gradient(0deg, rgba(0, 0, 0, 0), rgba(0, 0, 0, 0))',
      hovered: 'linear-gradient(0deg, rgba(0, 0, 0, 0.15), rgba(0, 0, 0, 0.15))',
      pressed: 'linear-gradient(0deg, rgba(0, 0, 0, 0.25), rgba(0, 0, 0, 0.25))',
      disabled: 'linear-gradient(0deg, rgba(0, 0, 0, 0), rgba(0, 0, 0, 0))',
    },
    backgroundColors: {
      brand: {
        normal: colors.brand.primary.medium,
        hovered: colors.brand.primary.medium,
        pressed: colors.brand.primary.medium,
        disabled: colors.base.onContrast.medium,
      },
      outline: {
        normal: colors.transparent,
        hovered: colors.brand.primary.medium,
        pressed: colors.brand.primary.medium,
        disabled: colors.transparent,
        active: colors.brand.primary.medium,
      },
      primary: {
        normal: colors.transparent,
        hovered: colors.transparent,
        pressed: colors.transparent,
        disabled: colors.transparent,
        active: colors.base.transparent.dark25,
      },
      secondary: {
        normal: colors.brand.secondary.dark,
        hovered: colors.brand.secondary.dark,
        pressed: colors.brand.secondary.dark,
        disabled: colors.base.onContrast.medium,
      },
      muted: {
        normal: colors.base.background.surface1,
        hovered: colors.brand.primary.medium,
        pressed: colors.brand.primary.medium,
        disabled: colors.base.onContrast.medium,
      },
      negative: {
        normal: colors.accents.error.medium,
        hovered: colors.accents.error.medium,
        pressed: colors.accents.error.medium,
        disabled: colors.base.onContrast.medium,
      },
      negativePrimary: {
        normal: colors.transparent,
        hovered: colors.transparent,
        pressed: colors.transparent,
        disabled: colors.transparent,
      },
      positive: {
        normal: colors.accents.success.medium,
        hovered: colors.accents.success.medium,
        pressed: colors.accents.success.medium,
        disabled: colors.base.onContrast.medium,
      },
      premium: {
        normal: colors.premium.background.normal,
        hovered: colors.premium.background.normal,
        pressed: colors.premium.background.normal,
        disabled: colors.base.onContrast.medium,
      },
    },
    borderColors: {
      brand: {
        normal: colors.brand.primary.medium,
        hovered: colors.transparent,
        pressed: colors.transparent,
        disabled: colors.base.onContrast.medium,
      },
      outline: {
        normal: colors.base.onBase.strokes,
        hovered: colors.transparent,
        pressed: colors.transparent,
        disabled: colors.base.onBase.disabled,
      },
      primary: {
        normal: colors.transparent,
        hovered: colors.transparent,
        pressed: colors.transparent,
        disabled: colors.transparent,
      },
      secondary: {
        normal: colors.brand.secondary.dark,
        hovered: colors.transparent,
        pressed: colors.transparent,
        disabled: colors.base.onContrast.medium,
      },
      muted: {
        normal: colors.base.background.surface1,
        hovered: colors.transparent,
        pressed: colors.transparent,
        disabled: colors.base.onContrast.medium,
      },
      negative: {
        normal: colors.accents.error.medium,
        hovered: colors.transparent,
        pressed: colors.transparent,
        disabled: colors.base.onContrast.medium,
      },
      negativePrimary: {
        normal: colors.transparent,
        hovered: colors.transparent,
        pressed: colors.transparent,
        disabled: colors.transparent,
      },
      positive: {
        normal: colors.accents.success.medium,
        hovered: colors.transparent,
        pressed: colors.transparent,
        disabled: colors.base.onContrast.medium,
      },
      premium: {
        normal: colors.none,
        hovered: colors.none,
        pressed: colors.none,
        disabled: colors.base.onContrast.medium,
      },
    },
    colors: {
      brand: {
        normal: colors.white,
        hovered: colors.white,
        pressed: colors.base.onBase.medium,
        disabled: colors.base.onBase.low,
      },
      outline: {
        normal: colors.white,
        hovered: colors.white,
        pressed: colors.base.onBase.medium,
        disabled: colors.base.onBase.disabled,
        active: colors.white,
      },
      primary: {
        normal: colors.white,
        hovered: colors.white,
        pressed: colors.white,
        disabled: colors.base.onBase.disabled,
      },
      secondary: {
        normal: colors.white,
        hovered: colors.white,
        pressed: colors.base.onBase.medium,
        disabled: colors.base.onBase.low,
      },
      muted: {
        normal: colors.white,
        hovered: colors.white,
        pressed: colors.base.onBase.medium,
        disabled: colors.base.onBase.low,
      },
      negative: {
        normal: colors.white,
        hovered: colors.white,
        pressed: colors.base.onBase.medium,
        disabled: colors.base.onBase.low,
      },
      negativePrimary: {
        normal: colors.accents.error.main,
        hovered: colors.accents.error.medium,
        pressed: colors.accents.error.deep,
        disabled: colors.base.onBase.disabled,
      },
      positive: {
        normal: colors.white,
        hovered: colors.white,
        pressed: colors.base.onBase.medium,
        disabled: colors.base.onBase.low,
      },
      premium: {
        normal: colors.white,
        hovered: colors.white,
        pressed: colors.base.onBase.medium,
        disabled: colors.base.onBase.low,
      },
    },
  },
};
